--
-- Oath official mod, by permission of Leder Games.
--
-- Created and maintained by AgentElrond.  Latest update:  2020
--
-- This file contains card data so that the main script file can be shorter.
--

function onLoad()
  cardsTable = {
    -- Site cards have their own save ID numbering system except for 255, which is shared with denizen / edifice / ruin cards.
    ["Mine"]                     = { saveid =  0, ttscardid = "10000", cardtype = "Site", capacity = 1, relicCount = 1 },
    ["Salt Flats"]               = { saveid =  1, ttscardid = "10001", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Fertile Valley"]           = { saveid =  2, ttscardid = "10002", cardtype = "Site", capacity = 3, relicCount = 0 },
    ["Barren Coast"]             = { saveid =  3, ttscardid = "10003", cardtype = "Site", capacity = 1, relicCount = 1 },
    ["Plains"]                   = { saveid =  4, ttscardid = "10004", cardtype = "Site", capacity = 3, relicCount = 0 },
    ["River"]                    = { saveid =  5, ttscardid = "10005", cardtype = "Site", capacity = 2, relicCount = 0 },
    ["Steppe"]                   = { saveid =  6, ttscardid = "10006", cardtype = "Site", capacity = 1, relicCount = 1 },
    ["Mountain"]                 = { saveid =  7, ttscardid = "10007", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Lush Coast"]               = { saveid =  8, ttscardid = "10100", cardtype = "Site", capacity = 3, relicCount = 0 },
    ["Marshes"]                  = { saveid =  9, ttscardid = "10101", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Wastes"]                   = { saveid = 10, ttscardid = "10102", cardtype = "Site", capacity = 1, relicCount = 2 },
    ["Rocky Coast"]              = { saveid = 11, ttscardid = "10103", cardtype = "Site", capacity = 2, relicCount = 0 },
    ["Narrow Pass"]              = { saveid = 12, ttscardid = "10104", cardtype = "Site", capacity = 1, relicCount = 1 },
    ["Charming Valley"]          = { saveid = 13, ttscardid = "10105", cardtype = "Site", capacity = 3, relicCount = 0 },
    ["Deep Woods"]               = { saveid = 14, ttscardid = "10106", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Standing Stones"]          = { saveid = 15, ttscardid = "10107", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Ancient City"]             = { saveid = 16, ttscardid = "10200", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["The Drowned City"]         = { saveid = 17, ttscardid = "10201", cardtype = "Site", capacity = 0, relicCount = 2 },
    ["Great Slum"]               = { saveid = 18, ttscardid = "10202", cardtype = "Site", capacity = 3, relicCount = 0 },
    ["Buried Giant"]             = { saveid = 19, ttscardid = "10203", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Imperial Seat"]            = { saveid = 20, ttscardid = "10204", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["Shrouded Wood"]            = { saveid = 21, ttscardid = "10205", cardtype = "Site", capacity = 2, relicCount = 1 },
    ["The Hidden Place"]         = { saveid = 22, ttscardid = "10206", cardtype = "Site", capacity = 2, relicCount = 1 },
    -- The 24th site card slot is currently unused.
    -- TODO if it is ever used, NUM_TOTAL_SITES needs updated in the main Lua script.
    --["UNUSED"]                = { saveid = 23, ttscardid = "10207", cardtype = "Site", capacity = 0 },
    -- Facedown site cards have 24 added to their saveid.

    -- Denizen, edifice, ruin, and vision cards all share the same save ID numbering system.
    -- This is done to keep as many open spots as possible in the 256 save IDs for a byte.
    ["Wrestlers"]                = { saveid =   0, ttscardid = "11000", suit = "Order", cardtype = "Denizen" },
    ["Battle Honors"]            = { saveid =   1, ttscardid = "11001", suit = "Order", cardtype = "Denizen" },
    ["Bear Traps"]               = { saveid =   2, ttscardid = "11002", suit = "Order", cardtype = "Denizen" },
    ["Longbows"]                 = { saveid =   3, ttscardid = "11003", suit = "Order", cardtype = "Denizen" },
    ["Keep"]                     = { saveid =   4, ttscardid = "11004", suit = "Order", cardtype = "Denizen" },
    ["Pressgangs"]               = { saveid =   5, ttscardid = "11005", suit = "Order", cardtype = "Denizen" },
    ["Garrison"]                 = { saveid =   6, ttscardid = "11006", suit = "Order", cardtype = "Denizen" },
    ["Scouts"]                   = { saveid =   7, ttscardid = "11007", suit = "Order", cardtype = "Denizen" },
    ["Alchemist"]                = { saveid =   8, ttscardid = "11008", suit = "Arcane", cardtype = "Denizen" },
    ["Martial Culture"]          = { saveid =   9, ttscardid = "11009", suit = "Order", cardtype = "Denizen" },
    ["Errand Boy"]               = { saveid =  10, ttscardid = "11010", suit = "Beast", cardtype = "Denizen" },
    ["Mercenaries"]              = { saveid =  11, ttscardid = "11011", suit = "Discord", cardtype = "Denizen" },
    ["Tinker's Fair"]            = { saveid =  12, ttscardid = "11012", suit = "Hearth", cardtype = "Denizen" },
    ["Rain Boots"]               = { saveid =  13, ttscardid = "11013", suit = "Nomad", cardtype = "Denizen" },
    ["A Small Favor"]            = { saveid =  14, ttscardid = "11014", suit = "Discord", cardtype = "Denizen" },
    ["Second Wind"]              = { saveid =  15, ttscardid = "11015", suit = "Discord", cardtype = "Denizen" },
    ["Gossip"]                   = { saveid =  16, ttscardid = "11016", suit = "Discord", cardtype = "Denizen" },
    ["Key to the City"]          = { saveid =  17, ttscardid = "11017", suit = "Discord", cardtype = "Denizen" },
    ["Scryer"]                   = { saveid =  18, ttscardid = "11018", suit = "Discord", cardtype = "Denizen" },
    ["Disgraced Captain"]        = { saveid =  19, ttscardid = "11019", suit = "Discord", cardtype = "Denizen" },
    ["Naysayers"]                = { saveid =  20, ttscardid = "11100", suit = "Discord", cardtype = "Denizen" },
    ["Book Burning"]             = { saveid =  21, ttscardid = "11101", suit = "Discord", cardtype = "Denizen" },
    ["Ancient Binding"]          = { saveid =  22, ttscardid = "11102", suit = "Nomad", cardtype = "Denizen" },
    ["Horse Archers"]            = { saveid =  23, ttscardid = "11103", suit = "Nomad", cardtype = "Denizen" },
    ["Warning Signals"]          = { saveid =  24, ttscardid = "11104", suit = "Nomad", cardtype = "Denizen" },
    ["Elders"]                   = { saveid =  25, ttscardid = "11105", suit = "Nomad", cardtype = "Denizen" },
    ["The Gathering"]            = { saveid =  26, ttscardid = "11106", suit = "Nomad", cardtype = "Denizen" },
    ["Faithful Friend"]          = { saveid =  27, ttscardid = "11107", suit = "Nomad", cardtype = "Denizen" },
    ["Tents"]                    = { saveid =  28, ttscardid = "11108", suit = "Nomad", cardtype = "Denizen" },
    ["Great Herd"]               = { saveid =  29, ttscardid = "11109", suit = "Nomad", cardtype = "Denizen" },
    ["Fire Talkers"]             = { saveid =  30, ttscardid = "11110", suit = "Arcane", cardtype = "Denizen" },
    ["Magician's Code"]          = { saveid =  31, ttscardid = "11111", suit = "Arcane", cardtype = "Denizen" },
    ["Spirit Snare"]             = { saveid =  32, ttscardid = "11112", suit = "Arcane", cardtype = "Denizen" },
    ["Wizard School"]            = { saveid =  33, ttscardid = "11113", suit = "Arcane", cardtype = "Denizen" },
    ["Dazzle"]                   = { saveid =  34, ttscardid = "11114", suit = "Arcane", cardtype = "Denizen" },
    ["Acting Troupe"]            = { saveid =  35, ttscardid = "11115", suit = "Arcane", cardtype = "Denizen" },
    ["Taming Charm"]             = { saveid =  36, ttscardid = "11116", suit = "Arcane", cardtype = "Denizen" },
    ["Inquisitor"]               = { saveid =  37, ttscardid = "11117", suit = "Arcane", cardtype = "Denizen" },
    ["Wolves"]                   = { saveid =  38, ttscardid = "11118", suit = "Beast", cardtype = "Denizen" },
    ["Animal Playmates"]         = { saveid =  39, ttscardid = "11119", suit = "Beast", cardtype = "Denizen" },
    ["True Names"]               = { saveid =  40, ttscardid = "11200", suit = "Beast", cardtype = "Denizen" },
    ["The Old Oak"]              = { saveid =  41, ttscardid = "11201", suit = "Beast", cardtype = "Denizen" },
    ["Forest Paths"]             = { saveid =  42, ttscardid = "11202", suit = "Beast", cardtype = "Denizen" },
    ["Long-Lost Heir"]           = { saveid =  43, ttscardid = "11203", suit = "Beast", cardtype = "Denizen" },
    ["Rangers"]                  = { saveid =  44, ttscardid = "11204", suit = "Beast", cardtype = "Denizen" },
    ["Roving Terror"]            = { saveid =  45, ttscardid = "11205", suit = "Beast", cardtype = "Denizen" },
    ["Wayside Inn"]              = { saveid =  46, ttscardid = "11206", suit = "Hearth", cardtype = "Denizen" },
    ["Extra Provisions"]         = { saveid =  47, ttscardid = "11207", suit = "Hearth", cardtype = "Denizen" },
    ["Memory of Home"]           = { saveid =  48, ttscardid = "11208", suit = "Hearth", cardtype = "Denizen" },
    ["Welcoming Party"]          = { saveid =  49, ttscardid = "11209", suit = "Hearth", cardtype = "Denizen" },
    ["Traveling Doctor"]         = { saveid =  50, ttscardid = "11210", suit = "Hearth", cardtype = "Denizen" },
    ["Storyteller"]              = { saveid =  51, ttscardid = "11211", suit = "Hearth", cardtype = "Denizen" },
    ["Armed Mob"]                = { saveid =  52, ttscardid = "11212", suit = "Hearth", cardtype = "Denizen" },
    ["Tavern Songs"]             = { saveid =  53, ttscardid = "11213", suit = "Hearth", cardtype = "Denizen" },
    ["Secret Signal"]            = { saveid =  54, ttscardid = "11214", suit = "Arcane", cardtype = "Denizen" },
    ["Augury"]                   = { saveid =  55, ttscardid = "11215", suit = "Arcane", cardtype = "Denizen" },
    ["Rusting Ray"]              = { saveid =  56, ttscardid = "11216", suit = "Arcane", cardtype = "Denizen" },
    ["Portal"]                   = { saveid =  57, ttscardid = "11217", suit = "Arcane", cardtype = "Denizen" },
    ["Billowing Fog"]            = { saveid =  58, ttscardid = "11218", suit = "Arcane", cardtype = "Denizen" },
    ["Kindred Warriors"]         = { saveid =  59, ttscardid = "11219", suit = "Arcane", cardtype = "Denizen" },
    ["Terror Spells"]            = { saveid =  60, ttscardid = "11300", suit = "Arcane", cardtype = "Denizen" },
    ["Blood Pact"]               = { saveid =  61, ttscardid = "11301", suit = "Arcane", cardtype = "Denizen" },
    ["Revelation"]               = { saveid =  62, ttscardid = "11302", suit = "Arcane", cardtype = "Denizen" },
    ["Observatory"]              = { saveid =  63, ttscardid = "11303", suit = "Arcane", cardtype = "Denizen" },
    ["Plague Engines"]           = { saveid =  64, ttscardid = "11304", suit = "Arcane", cardtype = "Denizen" },
    ["Gleaming Armor"]           = { saveid =  65, ttscardid = "11305", suit = "Arcane", cardtype = "Denizen" },
    ["Bewitch"]                  = { saveid =  66, ttscardid = "11306", suit = "Arcane", cardtype = "Denizen" },
    ["Jinx"]                     = { saveid =  67, ttscardid = "11307", suit = "Arcane", cardtype = "Denizen" },
    ["Tutor"]                    = { saveid =  68, ttscardid = "11308", suit = "Arcane", cardtype = "Denizen" },
    ["Dream Thief"]              = { saveid =  69, ttscardid = "11309", suit = "Arcane", cardtype = "Denizen" },
    ["Cracking Ground"]          = { saveid =  70, ttscardid = "11310", suit = "Arcane", cardtype = "Denizen" },
    ["Sealing Ward"]             = { saveid =  71, ttscardid = "11311", suit = "Arcane", cardtype = "Denizen" },
    ["Initiation Rite"]          = { saveid =  72, ttscardid = "11312", suit = "Arcane", cardtype = "Denizen" },
    ["Vow of Silence"]           = { saveid =  73, ttscardid = "11313", suit = "Arcane", cardtype = "Denizen" },
    ["Forgotten Vault"]          = { saveid =  74, ttscardid = "11314", suit = "Arcane", cardtype = "Denizen" },
    ["Map Library"]              = { saveid =  75, ttscardid = "11315", suit = "Arcane", cardtype = "Denizen" },
    ["Witch's Bargain"]          = { saveid =  76, ttscardid = "11316", suit = "Arcane", cardtype = "Denizen" },
    ["Master of Disguise"]       = { saveid =  77, ttscardid = "11317", suit = "Arcane", cardtype = "Denizen" },
    ["Charlatans"]               = { saveid =  78, ttscardid = "11318", suit = "Discord", cardtype = "Denizen" },
    ["Assassin"]                 = { saveid =  79, ttscardid = "11319", suit = "Discord", cardtype = "Denizen" },
    ["Downtrodden"]              = { saveid =  80, ttscardid = "11400", suit = "Discord", cardtype = "Denizen" },
    ["Blackmail"]                = { saveid =  81, ttscardid = "11401", suit = "Discord", cardtype = "Denizen" },
    ["Cracked Sage"]             = { saveid =  82, ttscardid = "11402", suit = "Discord", cardtype = "Denizen" },
    ["Dissent"]                  = { saveid =  83, ttscardid = "11403", suit = "Discord", cardtype = "Denizen" },
    ["False Prophet"]            = { saveid =  84, ttscardid = "11404", suit = "Discord", cardtype = "Denizen" },
    ["Vow of Renewal"]           = { saveid =  85, ttscardid = "11405", suit = "Discord", cardtype = "Denizen" },
    ["Zealots"]                  = { saveid =  86, ttscardid = "11406", suit = "Discord", cardtype = "Denizen" },
    ["Royal Ambitions"]          = { saveid =  87, ttscardid = "11407", suit = "Discord", cardtype = "Denizen" },
    ["Salt the Earth"]           = { saveid =  88, ttscardid = "11408", suit = "Discord", cardtype = "Denizen" },
    ["Beast Tamer"]              = { saveid =  89, ttscardid = "11409", suit = "Discord", cardtype = "Denizen" },
    ["Riots"]                    = { saveid =  90, ttscardid = "11410", suit = "Discord", cardtype = "Denizen" },
    ["Silver Tongue"]            = { saveid =  91, ttscardid = "11411", suit = "Discord", cardtype = "Denizen" },
    ["Gambling Hall"]            = { saveid =  92, ttscardid = "11412", suit = "Discord", cardtype = "Denizen" },
    ["Boiling Lake"]             = { saveid =  93, ttscardid = "11413", suit = "Discord", cardtype = "Denizen" },
    ["Relic Thief"]              = { saveid =  94, ttscardid = "11414", suit = "Discord", cardtype = "Denizen" },
    ["Enchantress"]              = { saveid =  95, ttscardid = "11415", suit = "Discord", cardtype = "Denizen" },
    ["Insomnia"]                 = { saveid =  96, ttscardid = "11416", suit = "Discord", cardtype = "Denizen" },
    ["Surprise Attack"]          = { saveid =  97, ttscardid = "11417", suit = "Discord", cardtype = "Denizen" },
    ["Sleight of Hand"]          = { saveid =  98, ttscardid = "11418", suit = "Discord", cardtype = "Denizen" },
    ["Bandit King"]              = { saveid =  99, ttscardid = "11419", suit = "Discord", cardtype = "Denizen" },
    ["Cult of Chaos"]            = { saveid = 100, ttscardid = "11500", suit = "Discord", cardtype = "Denizen" },
    ["Slander"]                  = { saveid = 101, ttscardid = "11501", suit = "Discord", cardtype = "Denizen" },
    ["Code of Honor"]            = { saveid = 102, ttscardid = "11502", suit = "Order", cardtype = "Denizen" },
    ["Outriders"]                = { saveid = 103, ttscardid = "11503", suit = "Order", cardtype = "Denizen" },
    ["Messenger"]                = { saveid = 104, ttscardid = "11504", suit = "Order", cardtype = "Denizen" },
    ["Field Promotion"]          = { saveid = 105, ttscardid = "11505", suit = "Order", cardtype = "Denizen" },
    ["Palanquin"]                = { saveid = 106, ttscardid = "11506", suit = "Order", cardtype = "Denizen" },
    ["Shield Wall"]              = { saveid = 107, ttscardid = "11507", suit = "Order", cardtype = "Denizen" },
    ["Military Parade"]          = { saveid = 108, ttscardid = "11508", suit = "Order", cardtype = "Denizen" },
    ["Tome Guardians"]           = { saveid = 109, ttscardid = "11509", suit = "Order", cardtype = "Denizen" },
    ["Tyrant"]                   = { saveid = 110, ttscardid = "11510", suit = "Order", cardtype = "Denizen" },
    ["Secret Police"]            = { saveid = 111, ttscardid = "11511", suit = "Order", cardtype = "Denizen" },
    ["Forced Labor"]             = { saveid = 112, ttscardid = "11512", suit = "Order", cardtype = "Denizen" },
    ["Specialist"]               = { saveid = 113, ttscardid = "11513", suit = "Order", cardtype = "Denizen" },
    ["Captains"]                 = { saveid = 114, ttscardid = "11514", suit = "Order", cardtype = "Denizen" },
    ["Siege Engines"]            = { saveid = 115, ttscardid = "11515", suit = "Order", cardtype = "Denizen" },
    ["Royal Tax"]                = { saveid = 116, ttscardid = "11516", suit = "Order", cardtype = "Denizen" },
    ["Toll Roads"]               = { saveid = 117, ttscardid = "11517", suit = "Order", cardtype = "Denizen" },
    ["Curfew"]                   = { saveid = 118, ttscardid = "11518", suit = "Order", cardtype = "Denizen" },
    ["Knights Errant"]           = { saveid = 119, ttscardid = "11519", suit = "Order", cardtype = "Denizen" },
    ["Vow of Obedience"]         = { saveid = 120, ttscardid = "11600", suit = "Order", cardtype = "Denizen" },
    ["Hunting Party"]            = { saveid = 121, ttscardid = "11601", suit = "Order", cardtype = "Denizen" },
    ["Council Seat"]             = { saveid = 122, ttscardid = "11602", suit = "Order", cardtype = "Denizen" },
    ["Encirclement"]             = { saveid = 123, ttscardid = "11603", suit = "Order", cardtype = "Denizen" },
    ["Peace Envoy"]              = { saveid = 124, ttscardid = "11604", suit = "Order", cardtype = "Denizen" },
    ["Relic Hunter"]             = { saveid = 125, ttscardid = "11605", suit = "Order", cardtype = "Denizen" },
    ["Homesteaders"]             = { saveid = 126, ttscardid = "11606", suit = "Hearth", cardtype = "Denizen" },
    ["Crop Rotation"]            = { saveid = 127, ttscardid = "11607", suit = "Hearth", cardtype = "Denizen" },
    ["A Round of Ale"]           = { saveid = 128, ttscardid = "11608", suit = "Hearth", cardtype = "Denizen" },
    ["Land Warden"]              = { saveid = 129, ttscardid = "11609", suit = "Hearth", cardtype = "Denizen" },
    ["Charming Friend"]          = { saveid = 130, ttscardid = "11610", suit = "Hearth", cardtype = "Denizen" },
    ["Village Constable"]        = { saveid = 131, ttscardid = "11611", suit = "Hearth", cardtype = "Denizen" },
    ["Family Heirloom"]          = { saveid = 132, ttscardid = "11612", suit = "Hearth", cardtype = "Denizen" },
    ["News from Afar"]           = { saveid = 133, ttscardid = "11613", suit = "Hearth", cardtype = "Denizen" },
    ["Levelers"]                 = { saveid = 134, ttscardid = "11614", suit = "Hearth", cardtype = "Denizen" },
    ["Fabled Feast"]             = { saveid = 135, ttscardid = "11615", suit = "Hearth", cardtype = "Denizen" },
    ["The Great Levy"]           = { saveid = 136, ttscardid = "11616", suit = "Hearth", cardtype = "Denizen" },
    ["Hearts and Minds"]         = { saveid = 137, ttscardid = "11617", suit = "Hearth", cardtype = "Denizen" },
    ["Relic Breaker"]            = { saveid = 138, ttscardid = "11618", suit = "Hearth", cardtype = "Denizen" },
    ["Book Binders"]             = { saveid = 139, ttscardid = "11619", suit = "Hearth", cardtype = "Denizen" },
    ["Ballot Box"]               = { saveid = 140, ttscardid = "11700", suit = "Hearth", cardtype = "Denizen" },
    ["Saddle Makers"]            = { saveid = 141, ttscardid = "11701", suit = "Hearth", cardtype = "Denizen" },
    ["Squires"]                  = { saveid = 142, ttscardid = "11702", suit = "Hearth", cardtype = "Denizen" },
    ["Rowdy Pub"]                = { saveid = 143, ttscardid = "11703", suit = "Hearth", cardtype = "Denizen" },
    ["Vow of Peace"]             = { saveid = 144, ttscardid = "11704", suit = "Hearth", cardtype = "Denizen" },
    ["Deed Writer"]              = { saveid = 145, ttscardid = "11705", suit = "Hearth", cardtype = "Denizen" },
    ["Salad Days"]               = { saveid = 146, ttscardid = "11706", suit = "Hearth", cardtype = "Denizen" },
    ["Marriage"]                 = { saveid = 147, ttscardid = "11707", suit = "Hearth", cardtype = "Denizen" },
    ["Hospital"]                 = { saveid = 148, ttscardid = "11708", suit = "Hearth", cardtype = "Denizen" },
    ["Awaited Return"]           = { saveid = 149, ttscardid = "11709", suit = "Hearth", cardtype = "Denizen" },
    ["Convoys"]                  = { saveid = 150, ttscardid = "11710", suit = "Nomad", cardtype = "Denizen" },
    ["Vow of Kinship"]           = { saveid = 151, ttscardid = "11711", suit = "Nomad", cardtype = "Denizen" },
    ["Wild Mounts"]              = { saveid = 152, ttscardid = "11712", suit = "Nomad", cardtype = "Denizen" },
    ["Lancers"]                  = { saveid = 153, ttscardid = "11713", suit = "Nomad", cardtype = "Denizen" },
    ["Mountain Giant"]           = { saveid = 154, ttscardid = "11714", suit = "Nomad", cardtype = "Denizen" },
    ["Rival Khan"]               = { saveid = 155, ttscardid = "11715", suit = "Nomad", cardtype = "Denizen" },
    ["Lost Tongue"]              = { saveid = 156, ttscardid = "11716", suit = "Nomad", cardtype = "Denizen" },
    ["Special Envoy"]            = { saveid = 157, ttscardid = "11717", suit = "Nomad", cardtype = "Denizen" },
    ["Homesick"]                 = { saveid = 158, ttscardid = "11718", suit = "Nomad", cardtype = "Denizen" },
    ["Oracle"]                   = { saveid = 159, ttscardid = "11719", suit = "Nomad", cardtype = "Denizen" },
    ["Pilgrimage"]               = { saveid = 160, ttscardid = "11800", suit = "Nomad", cardtype = "Denizen" },
    ["Spell Breaker"]            = { saveid = 161, ttscardid = "11801", suit = "Nomad", cardtype = "Denizen" },
    ["Mounted Patrol"]           = { saveid = 162, ttscardid = "11802", suit = "Nomad", cardtype = "Denizen" },
    ["Great Crusade"]            = { saveid = 163, ttscardid = "11803", suit = "Nomad", cardtype = "Denizen" },
    ["Ancient Bloodline"]        = { saveid = 164, ttscardid = "11804", suit = "Nomad", cardtype = "Denizen" },
    ["Ancient Pact"]             = { saveid = 165, ttscardid = "11805", suit = "Nomad", cardtype = "Denizen" },
    ["Storm Caller"]             = { saveid = 166, ttscardid = "11806", suit = "Nomad", cardtype = "Denizen" },
    ["Family Wagon"]             = { saveid = 167, ttscardid = "11807", suit = "Nomad", cardtype = "Denizen" },
    ["Way Station"]              = { saveid = 168, ttscardid = "11808", suit = "Nomad", cardtype = "Denizen" },
    ["Twin Brother"]             = { saveid = 169, ttscardid = "11809", suit = "Nomad", cardtype = "Denizen" },
    ["Hospitality"]              = { saveid = 170, ttscardid = "11810", suit = "Nomad", cardtype = "Denizen" },
    ["A Fast Steed"]             = { saveid = 171, ttscardid = "11811", suit = "Nomad", cardtype = "Denizen" },
    ["Relic Worship"]            = { saveid = 172, ttscardid = "11812", suit = "Nomad", cardtype = "Denizen" },
    ["Sacred Ground"]            = { saveid = 173, ttscardid = "11813", suit = "Nomad", cardtype = "Denizen" },
    ["Nature Worship"]           = { saveid = 174, ttscardid = "11814", suit = "Beast", cardtype = "Denizen" },
    ["Birdsong"]                 = { saveid = 175, ttscardid = "11815", suit = "Beast", cardtype = "Denizen" },
    ["Small Friends"]            = { saveid = 176, ttscardid = "11816", suit = "Beast", cardtype = "Denizen" },
    ["Grasping Vines"]           = { saveid = 177, ttscardid = "11817", suit = "Beast", cardtype = "Denizen" },
    ["Threatening Roar"]         = { saveid = 178, ttscardid = "11818", suit = "Beast", cardtype = "Denizen" },
    ["Fae Merchant"]             = { saveid = 179, ttscardid = "11819", suit = "Beast", cardtype = "Denizen" },
    ["Second Chance"]            = { saveid = 180, ttscardid = "11900", suit = "Beast", cardtype = "Denizen" },
    ["Pied Piper"]               = { saveid = 181, ttscardid = "11901", suit = "Beast", cardtype = "Denizen" },
    ["Mushrooms"]                = { saveid = 182, ttscardid = "11902", suit = "Beast", cardtype = "Denizen" },
    ["Insect Swarm"]             = { saveid = 183, ttscardid = "11903", suit = "Beast", cardtype = "Denizen" },
    ["Vow of Union"]             = { saveid = 184, ttscardid = "11904", suit = "Beast", cardtype = "Denizen" },
    ["Giant Python"]             = { saveid = 185, ttscardid = "11905", suit = "Beast", cardtype = "Denizen" },
    ["War Tortoise"]             = { saveid = 186, ttscardid = "11906", suit = "Beast", cardtype = "Denizen" },
    ["New Growth"]               = { saveid = 187, ttscardid = "11907", suit = "Beast", cardtype = "Denizen" },
    ["Wild Cry"]                 = { saveid = 188, ttscardid = "11908", suit = "Beast", cardtype = "Denizen" },
    ["Animal Host"]              = { saveid = 189, ttscardid = "11909", suit = "Beast", cardtype = "Denizen" },
    ["Memory of Nature"]         = { saveid = 190, ttscardid = "11910", suit = "Beast", cardtype = "Denizen" },
    ["Marsh Spirit"]             = { saveid = 191, ttscardid = "11911", suit = "Beast", cardtype = "Denizen" },
    ["Vow of Poverty"]           = { saveid = 192, ttscardid = "11912", suit = "Beast", cardtype = "Denizen" },
    ["Forest Council"]           = { saveid = 193, ttscardid = "11913", suit = "Beast", cardtype = "Denizen" },
    ["Walled Garden"]            = { saveid = 194, ttscardid = "11914", suit = "Beast", cardtype = "Denizen" },
    ["Vow of Beast-kin"]         = { saveid = 195, ttscardid = "11915", suit = "Beast", cardtype = "Denizen" },
    ["Bracken"]                  = { saveid = 196, ttscardid = "11916", suit = "Beast", cardtype = "Denizen" },
    ["Wild Allies"]              = { saveid = 197, ttscardid = "11917", suit = "Beast", cardtype = "Denizen" },
    -- TODO if more denizens are ever added, NUM_TOTAL_DENIZENS needs updated in the main Lua script.
    -- Note that edifices and ruins are two sides of the same card.  Each (saveid + 1) is reserved for the Ruin side.
    ["Sprawling Rampart / Bandit Rampart"]      = { saveid = 198, ttscardid = "12100", suit = "Order", cardtype = "EdificeRuin" },
    ["Hall of Debate / Hall of Liberation"]     = { saveid = 200, ttscardid = "12101", suit = "Hearth", cardtype = "EdificeRuin" },
    ["Forest Temple / Abandoned Temple"]        = { saveid = 202, ttscardid = "12102", suit = "Beast", cardtype = "EdificeRuin" },
    ["Festival District / Squalid District"]    = { saveid = 204, ttscardid = "12103", suit = "Discord", cardtype = "EdificeRuin" },
    ["Great Spire / Fallen Spire"]              = { saveid = 206, ttscardid = "12104", suit = "Arcane", cardtype = "EdificeRuin" },
    ["Ancient Forge / Broken Forge"]            = { saveid = 208, ttscardid = "12105", suit = "Nomad", cardtype = "EdificeRuin" },
    -- Note that visions still use the same saveid ordering system as normal cards.
    ["Dynasty"]                  = { saveid = 210, ttscardid = "12000", cardtype = "Vision" },
    ["Rebellion"]                = { saveid = 211, ttscardid = "12001", cardtype = "Vision" },
    ["Conspiracy"]               = { saveid = 212, ttscardid = "12002", cardtype = "Vision" },
    ["Faith"]                    = { saveid = 213, ttscardid = "12003", cardtype = "Vision" },
    ["Conquest"]                 = { saveid = 214, ttscardid = "12004", cardtype = "Vision" },
    -- Note that 215 and 216 were formerly reserved for privilege cards.
    ["The Darkest Secret"]                      = { saveid = 215, cardtype = "SuperRelic" },
    ["The People's Favor / The Mob's Favor"]    = { saveid = 216, cardtype = "SuperRelic" },
    -- Note that 217 was formerly the darkest secret.
    -- Note that relics still use the same saveid ordering system as normal cards.
    ["Sticky Fire"]              = { saveid = 218, ttscardid = "13100", cardtype = "Relic" },
    ["Cursed Cauldron"]          = { saveid = 219, ttscardid = "13101", cardtype = "Relic" },
    ["Brass Horse"]              = { saveid = 220, ttscardid = "13102", cardtype = "Relic" },
    ["Truthful Harp"]            = { saveid = 221, ttscardid = "13103", cardtype = "Relic" },
    ["Grand Mask"]               = { saveid = 222, ttscardid = "13104", cardtype = "Relic" },
    ["Horned Mask"]              = { saveid = 223, ttscardid = "13105", cardtype = "Relic" },
    ["Cup of Plenty"]            = { saveid = 224, ttscardid = "13106", cardtype = "Relic" },
    ["Whistle"]                  = { saveid = 225, ttscardid = "13107", cardtype = "Relic" },
    ["Dowsing Sticks"]           = { saveid = 226, ttscardid = "13108", cardtype = "Relic" },
    ["Cracked Horn"]             = { saveid = 227, ttscardid = "13109", cardtype = "Relic" },
    ["Bandit Crown"]             = { saveid = 228, ttscardid = "13110", cardtype = "Relic" },
    ["Banner of Devotion"]       = { saveid = 229, ttscardid = "13111", cardtype = "Relic" },
    ["Skeleton Key"]             = { saveid = 230, ttscardid = "13112", cardtype = "Relic" },
    ["Oracular Pig"]             = { saveid = 231, ttscardid = "13113", cardtype = "Relic" },
    ["Circlet of Command"]       = { saveid = 232, ttscardid = "13114", cardtype = "Relic" },
    ["Proof of Nobility"]        = { saveid = 233, ttscardid = "13115", cardtype = "Relic" },
    ["Map"]                      = { saveid = 234, ttscardid = "13116", cardtype = "Relic" },
    ["Obsidian Cage"]            = { saveid = 235, ttscardid = "13117", cardtype = "Relic" },
    ["Book of Records"]          = { saveid = 236, ttscardid = "13118", cardtype = "Relic" },
    ["Dragonskin Drum"]          = { saveid = 237, ttscardid = "13119", cardtype = "Relic" },

    -- This saveid is used for an empty site / denizen / edifice / ruin slot.
    ["NONE"]                     = { saveid = 255, cardtype = "None" }
  }
  Global.setTable("cardsTable", cardsTable)
  -- Attempt to release memory for this table.
  cardsTable = nil

  -- Save IDs of ruin cards for convenience in detecting whether they should spawn facedown.  The actual value of each entry does not matter here.
  ruinSaveIDs = {
    [199] = true,
    [201] = true,
    [203] = true,
    [205] = true,
    [207] = true,
    [209] = true
  }
  Global.setTable("ruinSaveIDs", ruinSaveIDs)
  -- Attempt to release memory for this table.
  ruinSaveIDs = nil

  -- For performance and/or ease of use, this table allows site lookup by saveid.
  siteCardCodes = {
      [0] = "Mine",
      [1] = "Salt Flats",
      [2] = "Fertile Valley",
      [3] = "Barren Coast",
      [4] = "Plains",
      [5] = "River",
      [6] = "Steppe",
      [7] = "Mountain",
      [8] = "Lush Coast",
      [9] = "Marshes",
     [10] = "Wastes",
     [11] = "Rocky Coast",
     [12] = "Narrow Pass",
     [13] = "Charming Valley",
     [14] = "Deep Woods",
     [15] = "Standing Stones",
     [16] = "Ancient City",
     [17] = "The Drowned City",
     [18] = "Great Slum",
     [19] = "Buried Giant",
     [20] = "Imperial Seat",
     [21] = "Shrouded Wood",
     [22] = "The Hidden Place",
    -- The 24th site card slot is currently unused.
    -- [23] = "UNUSED",
    -- The following are identical to the above, but represent facedown sites.
     [24] = "Mine",
     [25] = "Salt Flats",
     [26] = "Fertile Valley",
     [27] = "Barren Coast",
     [28] = "Plains",
     [29] = "River",
     [30] = "Steppe",
     [31] = "Mountain",
     [32] = "Lush Coast",
     [33] = "Marshes",
     [34] = "Wastes",
     [35] = "Rocky Coast",
     [36] = "Narrow Pass",
     [37] = "Charming Valley",
     [38] = "Deep Woods",
     [39] = "Standing Stones",
     [40] = "Ancient City",
     [41] = "The Drowned City",
     [42] = "Great Slum",
     [43] = "Buried Giant",
     [44] = "Imperial Seat",
     [45] = "Shrouded Wood",
     [46] = "The Hidden Place",
    -- The 24th site card slot is currently unused.
    -- [47] = "UNUSED",
    -- Empty.
    [255] = "NONE"
  }
  Global.setTable("siteCardCodes", siteCardCodes)
  -- Attempt to release memory for this table.
  siteCardCodes = nil

  -- For performance and/or ease of use, this table allows denizen, edifice, ruin, and vision card lookup by saveid.
  normalCardCodes = {
    -- Denizen cards.
      [0] = "Wrestlers",
      [1] = "Battle Honors",
      [2] = "Bear Traps",
      [3] = "Longbows",
      [4] = "Keep",
      [5] = "Pressgangs",
      [6] = "Garrison",
      [7] = "Scouts",
      [8] = "Alchemist",
      [9] = "Martial Culture",
     [10] = "Errand Boy",
     [11] = "Mercenaries",
     [12] = "Tinker's Fair",
     [13] = "Rain Boots",
     [14] = "A Small Favor",
     [15] = "Second Wind",
     [16] = "Gossip",
     [17] = "Key to the City",
     [18] = "Scryer",
     [19] = "Disgraced Captain",
     [20] = "Naysayers",
     [21] = "Book Burning",
     [22] = "Ancient Binding",
     [23] = "Horse Archers",
     [24] = "Warning Signals",
     [25] = "Elders",
     [26] = "The Gathering",
     [27] = "Faithful Friend",
     [28] = "Tents",
     [29] = "Great Herd",
     [30] = "Fire Talkers",
     [31] = "Magician's Code",
     [32] = "Spirit Snare",
     [33] = "Wizard School",
     [34] = "Dazzle",
     [35] = "Acting Troupe",
     [36] = "Taming Charm",
     [37] = "Inquisitor",
     [38] = "Wolves",
     [39] = "Animal Playmates",
     [40] = "True Names",
     [41] = "The Old Oak",
     [42] = "Forest Paths",
     [43] = "Long-Lost Heir",
     [44] = "Rangers",
     [45] = "Roving Terror",
     [46] = "Wayside Inn",
     [47] = "Extra Provisions",
     [48] = "Memory of Home",
     [49] = "Welcoming Party",
     [50] = "Traveling Doctor",
     [51] = "Storyteller",
     [52] = "Armed Mob",
     [53] = "Tavern Songs",
     [54] = "Secret Signal",
     [55] = "Augury",
     [56] = "Rusting Ray",
     [57] = "Portal",
     [58] = "Billowing Fog",
     [59] = "Kindred Warriors",
     [60] = "Terror Spells",
     [61] = "Blood Pact",
     [62] = "Revelation",
     [63] = "Observatory",
     [64] = "Plague Engines",
     [65] = "Gleaming Armor",
     [66] = "Bewitch",
     [67] = "Jinx",
     [68] = "Tutor",
     [69] = "Dream Thief",
     [70] = "Cracking Ground",
     [71] = "Sealing Ward",
     [72] = "Initiation Rite",
     [73] = "Vow of Silence",
     [74] = "Forgotten Vault",
     [75] = "Map Library",
     [76] = "Witch's Bargain",
     [77] = "Master of Disguise",
     [78] = "Charlatans",
     [79] = "Assassin",
     [80] = "Downtrodden",
     [81] = "Blackmail",
     [82] = "Cracked Sage",
     [83] = "Dissent",
     [84] = "False Prophet",
     [85] = "Vow of Renewal",
     [86] = "Zealots",
     [87] = "Royal Ambitions",
     [88] = "Salt the Earth",
     [89] = "Beast Tamer",
     [90] = "Riots",
     [91] = "Silver Tongue",
     [92] = "Gambling Hall",
     [93] = "Boiling Lake",
     [94] = "Relic Thief",
     [95] = "Enchantress",
     [96] = "Insomnia",
     [97] = "Surprise Attack",
     [98] = "Sleight of Hand",
     [99] = "Bandit King",
    [100] = "Cult of Chaos",
    [101] = "Slander",
    [102] = "Code of Honor",
    [103] = "Outriders",
    [104] = "Messenger",
    [105] = "Field Promotion",
    [106] = "Palanquin",
    [107] = "Shield Wall",
    [108] = "Military Parade",
    [109] = "Tome Guardians",
    [110] = "Tyrant",
    [111] = "Secret Police",
    [112] = "Forced Labor",
    [113] = "Specialist",
    [114] = "Captains",
    [115] = "Siege Engines",
    [116] = "Royal Tax",
    [117] = "Toll Roads",
    [118] = "Curfew",
    [119] = "Knights Errant",
    [120] = "Vow of Obedience",
    [121] = "Hunting Party",
    [122] = "Council Seat",
    [123] = "Encirclement",
    [124] = "Peace Envoy",
    [125] = "Relic Hunter",
    [126] = "Homesteaders",
    [127] = "Crop Rotation",
    [128] = "A Round of Ale",
    [129] = "Land Warden",
    [130] = "Charming Friend",
    [131] = "Village Constable",
    [132] = "Family Heirloom",
    [133] = "News from Afar",
    [134] = "Levelers",
    [135] = "Fabled Feast",
    [136] = "The Great Levy",
    [137] = "Hearts and Minds",
    [138] = "Relic Breaker",
    [139] = "Book Binders",
    [140] = "Ballot Box",
    [141] = "Saddle Makers",
    [142] = "Squires",
    [143] = "Rowdy Pub",
    [144] = "Vow of Peace",
    [145] = "Deed Writer",
    [146] = "Salad Days",
    [147] = "Marriage",
    [148] = "Hospital",
    [149] = "Awaited Return",
    [150] = "Convoys",
    [151] = "Vow of Kinship",
    [152] = "Wild Mounts",
    [153] = "Lancers",
    [154] = "Mountain Giant",
    [155] = "Rival Khan",
    [156] = "Lost Tongue",
    [157] = "Special Envoy",
    [158] = "Homesick",
    [159] = "Oracle",
    [160] = "Pilgrimage",
    [161] = "Spell Breaker",
    [162] = "Mounted Patrol",
    [163] = "Great Crusade",
    [164] = "Ancient Bloodline",
    [165] = "Ancient Pact",
    [166] = "Storm Caller",
    [167] = "Family Wagon",
    [168] = "Way Station",
    [169] = "Twin Brother",
    [170] = "Hospitality",
    [171] = "A Fast Steed",
    [172] = "Relic Worship",
    [173] = "Sacred Ground",
    [174] = "Nature Worship",
    [175] = "Birdsong",
    [176] = "Small Friends",
    [177] = "Grasping Vines",
    [178] = "Threatening Roar",
    [179] = "Fae Merchant",
    [180] = "Second Chance",
    [181] = "Pied Piper",
    [182] = "Mushrooms",
    [183] = "Insect Swarm",
    [184] = "Vow of Union",
    [185] = "Giant Python",
    [186] = "War Tortoise",
    [187] = "New Growth",
    [188] = "Wild Cry",
    [189] = "Animal Host",
    [190] = "Memory of Nature",
    [191] = "Marsh Spirit",
    [192] = "Vow of Poverty",
    [193] = "Forest Council",
    [194] = "Walled Garden",
    [195] = "Vow of Beast-kin",
    [196] = "Bracken",
    [197] = "Wild Allies",
    -- Edifices and ruins.
    [198] = "Sprawling Rampart / Bandit Rampart",
    [199] = "Sprawling Rampart / Bandit Rampart",
    [200] = "Hall of Debate / Hall of Liberation",
    [201] = "Hall of Debate / Hall of Liberation",
    [202] = "Forest Temple / Abandoned Temple",
    [203] = "Forest Temple / Abandoned Temple",
    [204] = "Festival District / Squalid District",
    [205] = "Festival District / Squalid District",
    [206] = "Great Spire / Fallen Spire",
    [207] = "Great Spire / Fallen Spire",
    [208] = "Ancient Forge / Broken Forge",
    [209] = "Ancient Forge / Broken Forge",
    -- Visions.
    [210] = "Dynasty",
    [211] = "Rebellion",
    [212] = "Conspiracy",
    [213] = "Faith",
    [214] = "Conquest",
    -- Note that 215 and 216 were formerly reserved for privilege cards.
    [215] = "The Darkest Secret",
    [216] = "The People's Favor / The Mob's Favor",
    -- Relics.
    -- Note that 217 was formerly the darkest secret.
    [218] = "Sticky Fire",
    [219] = "Cursed Cauldron",
    [220] = "Brass Horse",
    [221] = "Truthful Harp",
    [222] = "Grand Mask",
    [223] = "Horned Mask",
    [224] = "Cup of Plenty",
    [225] = "Whistle",
    [226] = "Dowsing Sticks",
    [227] = "Cracked Horn",
    [228] = "Bandit Crown",
    [229] = "Banner of Devotion",
    [230] = "Skeleton Key",
    [231] = "Oracular Pig",
    [232] = "Circlet of Command",
    [233] = "Proof of Nobility",
    [234] = "Map",
    [235] = "Obsidian Cage",
    [236] = "Book of Records",
    [237] = "Dragonskin Drum",
    -- Empty.
    [255] = "NONE"
  }
  Global.setTable("normalCardCodes", normalCardCodes)
  -- Attempt to release memory for this table.
  normalCardCodes = nil

  -- Site card back.
  siteBackURL                       = "http://tts.ledergames.com/Oath/cards/3_1_0/landBack.jpg"

  -- Standard Oath card back.
  normalBackURL                     = "http://tts.ledergames.com/Oath/cards/3_1_0/cardbackDefault.jpg"

  -- This table contains Tabletop Simulator deck info, indexed by ttsdeckid as referenced in cardsTable.
  ttsDeckInfo = {
    -- Site card decks.
    [100]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/lands.jpg", backimage = siteBackURL, deckwidth = 2, deckheight = 4, hasuniqueback = false },
    [101]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/lands2.jpg", backimage = siteBackURL, deckwidth = 2, deckheight = 4, hasuniqueback = false },
    [102]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/lands3.jpg", backimage = siteBackURL, deckwidth = 2, deckheight = 4, hasuniqueback = false },

    -- Denizen card decks.
    [110]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [111]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards2.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [112]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards3.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [113]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards4.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [114]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards5.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [115]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards6.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [116]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards7.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [117]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards8.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [118]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards9.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },
    [119]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cards10.jpg", backimage = normalBackURL, deckwidth = 5, deckheight = 4, hasuniqueback = false },

    -- Special deck for visions.
    [120]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/visions.jpg", backimage = "http://tts.ledergames.com/Oath/cards/3_1_0/cardbackVision.jpg", deckwidth = 5, deckheight = 4, hasuniqueback = false },
    -- Special deck for edifices.
    [121]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/edificeFront.jpg", backimage = "http://tts.ledergames.com/Oath/cards/3_1_0/edificeBack.jpg", deckwidth = 3, deckheight = 2, hasuniqueback = true },

    -- NOTE:  Deck ID 130 has been retired and was the old office deck.

    -- Relic deck.
    [131]   = { deckimage = "http://tts.ledergames.com/Oath/cards/3_1_0/relics.jpg", backimage = "http://tts.ledergames.com/Oath/cards/3_1_0/relicBack.jpg", deckwidth = 5, deckheight = 5, hasuniqueback = false }
  }
  Global.setTable("ttsDeckInfo", ttsDeckInfo)
  -- Attempt to release memory for this table.
  ttsDeckInfo = nil

  -- Mark data as available, indicating this object has finished loading.
  Global.setVar("dataIsAvailable", true)
end


